name: Application Deploying On AWS

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  VERSION: v1
  REGION: us-east-1
  IMAGE: 387385940921.dkr.ecr.us-east-1.amazonaws.com/flaskapp-simple-bank
  S3_BUCKET: s3://387385940921-devops-scripts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Banking App Repo
        uses: actions/checkout@v4
        with:
          repository: divaychauhan/banking-app-2-tier
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387385940921:role/github-action-deploy-role
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | \
          docker login --username AWS --password-stdin \
          387385940921.dkr.ecr.${{ env.REGION }}.amazonaws.com

          echo "Login Successful to ECR ✅"

      - name: Build and Push Image
        run: |
          docker build -t ${{ env.IMAGE }}:${{ env.VERSION }} .
          docker push ${{ env.IMAGE }}:${{ env.VERSION }}

          echo "Image Pushed: ${{ env.VERSION }} ✅"

      - name: Upload Docker Compose to S3
        run: |
          aws s3 cp docker-compose.yml \
            ${{ env.S3_BUCKET }}/docker-compose.yml \
            --region ${{ env.REGION }}

          echo "Docker Compose Uploaded ✅"