name: Application Deploying On AWS

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: v1
      REGION: us-east-1
      IMAGE: 387385940921.dkr.ecr.us-east-1.amazonaws.com/flaskapp-simple-bank
      S3_BUCKET: s3://387385940921-devops-scripts

    steps:
      - name: Checkout Banking App Repo
        uses: actions/checkout@v4
        with:
          repository: divaychauhan/banking-app-2-tier
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387385940921:role/github-action-deploy-role
          aws-region: ${{ env.REGION }}

      - name: Verify Environment Variables
        run: |
          echo "VERSION=$VERSION"
          echo "REGION=$REGION"
          echo "IMAGE=$IMAGE"
          echo "S3_BUCKET=$S3_BUCKET"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | \
          docker login --username AWS --password-stdin \
          387385940921.dkr.ecr.$REGION.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE:$VERSION .

      - name: Push Docker Image
        run: |
          docker push $IMAGE:$VERSION

      - name: Upload Docker Compose to S3
        run: |
          aws s3 cp docker-compose.yml $S3_BUCKET/docker-compose.yml --region $REGION

      - name: Deployment Complete
        run: echo "Application deployed successfully."